### PR TITLE
OD support for Download feature

### PR DESCRIPTION
**Pull request by nbeguier**
It's now possible to use od instead of xxd if the binary is not present.

### CODE REVIEW

**Comment by nbeguier** [comment]
On CentOS container (172.18.0.2) : 
```
docker run -it --rm centos /bin/bash
$ yum install nc
$ command -v xxd; echo $?  # Return 1
$ nc -lvvp 7777 -e /bin/bash
```

On the FFM client : 
```
nc 172.18.0.2 7777 !bypass
$ !download file.txt doxnloaded_file.txt
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.13k/6.13k [00:00<00:00, 104ko/s]

Local MD5:  e1ff9cee0ed7d457c11dca91b35fc142
Remote MD5: e1ff9cee0ed7d457c11dca91b35fc142
```

**Comment by JusticeRage** [comment]
I've made a few modifications to your PR. Could you allow me to [push commits to your branch](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so I can send you my modifications?

**Comment by nbeguier** [comment]
Are you sure this isn't already enabled ? Just in case, I've added you as a collaborater

**Comment by JusticeRage** [comment]
You're right, it was an issue on my end. Apologies!
I've pushed my updates.

**Comment by nbeguier** [comment]
Great !

**Pull request merged**
